"""
Metrics endpoint: returns evaluation results if available.
"""

from __future__ import annotations

import json
from pathlib import Path

from fastapi import APIRouter, HTTPException

from backend.schemas import MetricsResponse
from core.evaluator import ModelEvaluator

router = APIRouter()


@router.get("/metrics", response_model=MetricsResponse)
async def metrics():
    """
    Return the latest evaluation metrics.

    Reads from the evaluation.json file generated by scripts/evaluate.py.
    If no evaluation has been run, returns 404.
    """
    from backend.app import get_config_instance

    cfg = get_config_instance()
    run_dir = cfg.training.project_path / cfg.training.name

    eval_path = run_dir / "evaluation.json"
    if not eval_path.exists():
        # Search for any evaluation.json in runs/ directory
        candidates = list(cfg.training.project_path.glob("**/evaluation.json"))
        if candidates:
            eval_path = candidates[0]
            run_dir = eval_path.parent
        else:
            raise HTTPException(
                status_code=404,
                detail="No evaluation results found. Run: python scripts/evaluate.py --weights <path>",
            )

    with open(eval_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Optionally include training curves
    curves = ModelEvaluator.get_training_curves(str(run_dir))

    return MetricsResponse(
        precision=data.get("precision", 0),
        recall=data.get("recall", 0),
        map50=data.get("mAP@50", 0),
        map50_95=data.get("mAP@50-95", 0),
        f1_score=data.get("f1_score", 0),
        per_class=data.get("per_class", {}),
        model_info=data.get("model_info", {}),
        training_curves=curves if curves else None,
    )
